### ISSUE TITLE
resize callback only runs when element gets smaller

### ISSUE THREAD

**Issue by eloop** [nrako/react-component-resizable#3]
Hi, just stumbled across this component which does exactly what I need at the moment. However it seems to have a problem where it's not callbacking when an element expands. It's possible I'm not using it the right way, maybe an example or two would be useful. Thanks.

**Comment by nrako** [comment]
Yeah maybe I should... but in the meantime you can check this repo https://github.com/sdecima/javascript-detect-element-resize which highly inspired this component, there is some basic html tests within it.

Because the trick rely on css and onscroll event, you'll need to understand the mechanism and see if your own css have any side-effects on any of the `.resize-...`classes which would prevent the onscroll event to fire.

Also maybe there is an issue, but you'll have to be more clear as you mention expand and "gets smaller" and don't give any info on the env.

**Comment by jayfunk** [comment]
I think this issue should be resolved with the pull request I put in today. #4

**Comment by nrako** [comment]
Released 0.2.3, thx @jayfunk

**Comment by benjeffery** [comment]
I have this same problem with 0.2.3 - it seems to work by calling "resetTriggers" after "props.onResize" but I don't fully understand the technique.
